# Generated by Django 3.2.13 on 2023-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.IntegerField(),
        ),
    ]
