# Generated by Django 3.2.13 on 2023-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
