# Generated by Django 3.2.13 on 2023-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
